name: Android Build

on:
  workflow_dispatch:
    inputs:
      buildTag:
        description: 'Provide Build Version'
        required: true
        type: string

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    env:
      UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
        continue-on-error: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Create LFS file list
        run: |
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        with:
          path: .git/lfs
          key: ubuntu-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: ubuntu-lib-${{ hashFiles('Assets/**','Packages/**','ProjectSettings/**') }}
          restore-keys: |
            ubuntu-lib-

      - name: Inject deepgram.json (macOS/Linux)
        run: |
          mkdir -p Assets/StreamingAssets
          echo '${{ secrets.DEEPGRAM_JSON }}' > Assets/StreamingAssets/deepgram.json

      - name: Build Android
        uses: game-ci/unity-builder@v4.4.0
        continue-on-error: true
        with:
          unityVersion:   2022.3.45f1
          targetPlatform: Android
          buildName:      Metro
          buildMethod: BuildScript.BuildAndroid

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ github.event.inputs.buildTag }}
          path: build/android/Metro.apk
